name: Publish release

on:
  push:
    tags:
      - "*"

env:
  GIT_SSH_COMMAND: ssh -i $HOME/.ssh/aur -o UserKnownHostsFile=$HOME/.ssh/known_hosts

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: rust:latest

    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: cargo test --release

  publish:
    runs-on: ubuntu-latest
    container:
      image: rust:latest

    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Init SSH key and hosts
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_AUR_KEY }}
          name: aur
          known_hosts: ${{ secrets.KNOWN_HOSTS_AUR }}
      - name: Checkout pkgbuild submodule
        run: git submodule update --init --force --depth=1
      - name: Build binary
        run: cargo build --release
      - name: Generate tarball
        run: tar czf release.tar.gz share target/release/muso
      - name: Set VERSION environment variable
        run: |
          version=$(echo $GITHUB_REF | cut -d '/' -f3)
          echo "VERSION=$version" >> $GITHUB_ENV
      - name: Update PKGBUILD
        run: |
          sha256sum=$(sha256sum release.tar.gz | cut -d ' ' -f1)
          cd pkgbuild

          sed -i -E "s/(pkgver=).*/\1$VERSION/" PKGBUILD
          sed -i -E "s/(pkgrel=).*/\11/" PKGBUILD
          sed -i -E "s/(sha256sums=).*/\1('$sha256sum')/" PKGBUILD
        env:
          VERSION: ${{ env.VERSION }}
      - name: Generate .SRCINFO
        uses: ./.github/actions/generate_srcinfo
        with:
          target: pkgbuild
      - name: Publish to AUR
        run: |
          cd pkgbuild

          git config --local user.email "quebin31@gmail.com"
          git config --local user.name "Kevin (CI/CD)"
          git commit -m "updver: $VERSION" -a 
          git push origin HEAD:refs/heads/master
        env:
          VERSION: ${{ env.VERSION }}
      - name: Publish to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: release.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
